In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\nPython list Processing time: ",time.time()-start)

start = time.time()
np_array = np.arange(1000000)*2
print("\nNumpy Array Processign time: ",time.time()-start)


Python list Processing time:  0.0642082691192627

Numpy Array Processign time:  0.003699779510498047


In [ ]:
 df = np.genfromtxt( "SampleFile.csv",delimiter = ',')

In [ ]:
df.shape

(21, 2)

In [ ]:
df

array([[   nan,    nan],
       [ 8450.,    60.],
       [ 9600.,    20.],
       [11250.,    60.],
       [ 9550.,    70.],
       [14260.,    60.],
       [14115.,    50.],
       [10084.,    20.],
       [10382.,    60.],
       [ 6120.,    50.],
       [ 7420.,   190.],
       [11200.,    20.],
       [11924.,    60.],
       [12968.,    20.],
       [10652.,    20.],
       [10920.,    20.],
       [ 6120.,    45.],
       [11241.,    20.],
       [10791.,    90.],
       [13695.,    20.],
       [ 7560.,    20.]])

In [ ]:
np.insert(arr,2,[[2.0,4.5,6.6]])

ValueError: could not broadcast input array from shape (3,) into shape (1,)

In [ ]:
arr

array([[1.2, 2.4, 3.2],
       [4.5, 5.3, 2. ],
       [2. , 6. , 4.1],
       [3. , 4.9, 8. ]])

In [ ]:
rf

1.199999999999999956e+00  2.399999999999999911e+00  \
0                       4.5                       5.3   
1                       7.8                       8.9   

   3.100000000000000089e+00  
0                       6.7  
1                       9.0

In [ ]:
arr = np.array([(1,2,3),(4,5,6)])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
ar  = np.full((2,3),7)

In [ ]:
ar

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
arr = np.eye(5)

In [ ]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.linspace(0,100,6)

In [ ]:
arr

array([  0.,  20.,  40.,  60.,  80., 100.])

In [ ]:
arr = np.random.random((2,3))

In [ ]:
arr

array([[0.19220319, 0.89530325, 0.1890112 ],
       [0.87241395, 0.59475929, 0.2429695 ]])

In [ ]:
arr = np.random.random((2,3,3))

In [ ]:
arr

array([[[0.91226492, 0.50637949, 0.32183993],
        [0.94131555, 0.27514266, 0.90471507],
        [0.22888171, 0.00368714, 0.68972905]],

       [[0.65780289, 0.58149586, 0.87426803],
        [0.59926629, 0.24601972, 0.81879629],
        [0.35316677, 0.33988911, 0.50890839]]])

In [ ]:
arr =np.random.rand(6,7)*100

In [ ]:
arr

array([[58.67105786, 48.09951975, 58.13621588, 59.40944042, 22.47721076,
        95.18241614, 13.64793187],
       [45.17480886, 77.71045535, 32.89967141, 57.92895329, 91.35469312,
        88.29236752, 17.12025945],
       [83.51891619, 90.47759738, 50.36005857, 52.02215216, 47.91153297,
         7.47292788, 77.17049362],
       [57.9636256 , 24.22110279, 67.26054083,  3.62593567,  6.90254366,
        65.87553176,  7.30755447],
       [78.60434993, 57.09172859, 26.67983386, 69.92306306, 31.72033805,
        19.70880946,  1.44169142],
       [69.05688481, 30.48942067, 51.16625586,  9.34146286, 87.1676801 ,
        15.74132647,  1.81684113]])

In [ ]:
arr = np.array(["1","2","3"])
arr.dtype
s = arr.astype(int)

In [ ]:
s.dtype

dtype('int64')

In [ ]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [ ]:
arr = arr.tolist()

In [ ]:
type(arr)

list

In [ ]:
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None,
     like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not

In [ ]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])


In [ ]:
np.append(arr, [[26, 27, 28, 29, 30]], axis=0)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
np.insert(arr, 2, [100, 101, 102, 103, 104], axis=0)


array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [100, 101, 102, 103, 104],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25]])

In [ ]:
np.delete(arr, 3, axis=0)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [ ]:
np.delete(arr, 4, axis=1)


array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [ ]:
np.append(arr, [[26, 27, 28, 29]], axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 1

In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concat([arr1,arr2],axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

In [ ]:
(a<5)&(b>5)

ValueError: operands could not be broadcast together with shapes (6,) (2,3) 

In [ ]:
b

array([[ 7,  8,  9],
       [10, 11,  4]])

In [ ]:
arr = np.concatenate((a,b),axis = 1)

In [ ]:
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.split(a,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [ ]:
np.split(b,2)

[array([[7, 8, 9]]), array([[10, 11, 12]])]

In [ ]:
np.hsplit(a,3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

In [ ]:
(a<5)&(b>5)

array([[ True,  True,  True],
       [ True, False, False]])

In [ ]:
~a

array([[-2, -3, -4],
       [-5, -6, -7]])

In [ ]:
a[a<5]

array([1, 2, 3, 4])

In [ ]:
(a<3)|(b>5)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.add(a,1)

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.subtract(a,2)

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [ ]:
np.multiply(a,3)

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
np.divide(a,2)

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])

In [ ]:
print("\n The Size of Array: ",arr.size)


 The Size of Array:  6


In [ ]:
print("\n The Size of Array: ",arr.shape)


 The Size of Array:  (2, 3)


In [ ]:
print("\n The Size of Array: ",arr.ndim)


 The Size of Array:  2


In [ ]:
print("\n The Size of Array: ",arr.dtype)


 The Size of Array:  int64


In [ ]:
arr = np.array([[[1,2],
                 [3,4]]])

In [ ]:
print("\n The Size of Array: ",arr.dtype)


 The Size of Array:  int64


In [ ]:
numbers = [ 1,2,4,5,6,7]

indices = [0,2,4]
print(numbers[indices])
where_result = np.where(numbers>5)
print("Where_result: ", numbers[where_result])

TypeError: list indices must be integers or slices, not list

In [ ]:
import numpy as np

numbers = np.array([1, 2, 4, 5, 6, 7])       # Convert to NumPy array
# indices = np.array([0, 2, 4])                # Also NumPy array

# print(numbers[indices])                     # Output: [1 4 6]

where_result = np.where(numbers > 5)
print("Where_result:", numbers[where_result])  # Output: [6 7]

Where_result: [6 7]


In [ ]:
 import pandas as pd
import numpy as np

# Create the DataFrame
df = pd.DataFrame({
    'A': np.array([10, 20, 30, 40, 50]),
    'B': np.array([10, 20, 30, 40, 50]),
    'C': np.array([5.3, -3, 4.6, 7.9, -1]),
    'D': np.array([100, 64, 49, 81, 25])
})

print(df)


    A   B    C    D
0  10  10  5.3  100
1  20  20 -3.0   64
2  30  30  4.6   49
3  40  40  7.9   81
4  50  50 -1.0   25


In [ ]:
np.add(df['A'],df['B'])

0    12
1    24
2    36
3    48
4    60
dtype: int64

In [ ]:
np.subtract(df['A'],df['C'])

0     5
1    23
2    30
3    33
4    51
dtype: int64

In [ ]:
np.multiply(df['A'],df['C'])

0     50
1    -60
2      0
3    280
4    -50
dtype: int64

In [ ]:
np.divide(df['A'],df["C"])

0     2.000000
1    -6.666667
2          inf
3     5.714286
4   -50.000000
dtype: float64

In [ ]:
np.power(df['A'],df['B'])

0                  100
1               160000
2            729000000
3        6553600000000
4    97656250000000000
dtype: int64

In [ ]:
df

A   B  C    D
0  10  10  5  100
1  20  20 -3   64
2  30  30  0   49
3  40  40  7   81
4  50  50 -1   25

In [ ]:
df

A   B    C    D
0  10  10  5.3  100
1  20  20 -3.0   64
2  30  30  4.6   49
3  40  40  7.9   81
4  50  50 -1.0   25

In [ ]:
np.ceil(df['C'])

0    6.0
1   -3.0
2    5.0
3    8.0
4   -1.0
Name: C, dtype: float64

In [ ]:
np.floor(df['C'])

0    5.0
1   -3.0
2    4.0
3    7.0
4   -1.0
Name: C, dtype: float64

In [ ]:
np.round(df['C'])

0    5.0
1   -3.0
2    5.0
3    8.0
4   -1.0
Name: C, dtype: float64

In [ ]:
import csv
f = open("Book1.csv","r")
taxi_list = list(csv.reader(f))
taxi = np.array(taxi_list)

In [ ]:
taxi

array([['pickup_year', 'pickup_month', 'pickup_day', 'pickup_hour',
        'pickup_minute', 'passengers', 'distance', 'duration', 'tip',
        'fare', 'rate_code', 'store_and_fwd_flag', 'payment_type',
        'total_amount'],
       ['2016', '1', '1', '0', '11', '1', '3.5', '900', '0', '12.5', '1',
        'N', '1', '12.5'],
       ['2016', '1', '1', '0', '22', '1', '1.1', '300', '0', '5.5', '1',
        'N', '1', '5.5'],
       ['2016', '1', '1', '0', '33', '1', '2.2', '500', '0', '9', '1',
        'N', '2', '9'],
       ['2016', '1', '1', '0', '44', '2', '0.5', '150', '1', '4.5', '1',
        'N', '1', '5.5'],
       ['2016', '1', '1', '0', '55', '1', '3.7', '950', '2', '13.5', '1',
        'N', '1', '15.5']], dtype='<U18')

In [ ]:
taxi.shape

(6, 14)

In [ ]:
second = taxi[1]

In [ ]:
second

array(['2016', '1', '1', '0', '11', '1', '3.5', '900', '0', '12.5', '1',
       'N', '1', '12.5'], dtype='<U18')

In [ ]:
second_fourth_sixth_columns = taxi[:, cols]

NameError: name 'cols' is not defined

In [ ]:
import pandas as pd

# Create the DataFrame
df = pd.DataFrame({
    'vector_a_x': [1, -1, 7, 0, 2],
    'vector_a_y': [2, 0, 8, 5, -3]
})

print(df)


   vector_a_x  vector_a_y
0           1           2
1          -1           0
2           7           8
3           0           5
4           2          -3


In [ ]:
df['vector_a_x']/df['vector_a_y']

0    0.500000
1        -inf
2    0.875000
3    0.000000
4   -0.666667
dtype: float64

In [ ]:
arr = np.array([2,4,5,3,8,10])

In [ ]:
print(arr.min())

2


In [ ]:
arr = np.array([[1,2],[4,8],[9,20]])

In [ ]:
arr.shape

(3, 2)

In [ ]:
arr.max(axis = 1)

array([ 2,  8, 20])

In [ ]:
arr.max(axis = 0)

array([ 9, 20])

In [ ]:
arr  = np.array([2,4,6,8])<5

In [ ]:
arr

array([ True,  True, False, False])